print("Cadastro de Hábito")

id_habito = input("ID do hábito: ")
id_usuario = input("ID do usuário: ")
nome_habito = input("Nome do hábito: ")
descricao = input("Descrição: ")
frequencia = input("Frequência (ex: diário, semanal): ")
dias_semana = input("Dias da semana: ")
situacao_atual = input("Situação atual: ")
ativo = input("Ativo? (sim/não): ")
data_inicio = input("Data de início: ")
concluido = input("Concluído? (sim/não): ")
criado_em = input("Criado em: ")

print("\n--- Hábito cadastrado ---")
print("ID:", id_habito)
print("Usuário:", id_usuario)
print("Nome:", nome_habito)
print("Descrição:", descricao)
print("Frequência:", frequencia)
print("Dias semana:", dias_semana)
print("Situação atual:", situacao_atual)
print("Ativo:", ativo)
print("Início:", data_inicio)
print("Concluído:", concluido)
print("Criado em:", criado_em)
