print("Cadastro de Notificação")

id_notificacao = input("ID da notificação: ")
id_usuario = input("ID do usuário: ")
titulo = input("Título: ")
mensagem = input("Mensagem: ")
tipo = input("Tipo: ")
data_envio = input("Data de envio: ")
link = input("Link: ")
criado_em = input("Criado em: ")

print("\n--- Notificação cadastrada ---")
print("ID:", id_notificacao)
print("Usuário:", id_usuario)
print("Título:", titulo)
print("Mensagem:", mensagem)
print("Tipo:", tipo)
print("Data envio:", data_envio)
print("Link:", link)
print("Criado em:", criado_em)
