print("Cadastro de Projeto")

id_projeto = input("ID do projeto: ")
nome_projeto = input("Nome do projeto: ")
descricao = input("Descrição: ")
data_inicio = input("Data de início: ")
data_termino = input("Data de término: ")
id_usuario = input("ID do usuário: ")
cor_projeto = input("Cor do projeto: ")
criado_em = input("Criado em: ")

print("\n--- Projeto cadastrado ---")
print("ID:", id_projeto)
print("Nome:", nome_projeto)
print("Descrição:", descricao)
print("Início:", data_inicio)
print("Término:", data_termino)
print("Usuário:", id_usuario)
print("Cor:", cor_projeto)
print("Criado em:", criado_em)
