print("Cadastro de Tarefa")

id_tarefas = input("ID da tarefa: ")
titulo_tarefa = input("Título: ")
descricao_tarefa = input("Descrição: ")
data_criacao = input("Data de criação: ")
data_vencimento = input("Data de vencimento: ")
prioridade = input("Prioridade (número): ")
categoria = input("Categoria: ")
id_usuario = input("ID do usuário: ")
id_projeto = input("ID do projeto: ")
cor_projeto = input("Cor do projeto: ")
criado_em = input("Criado em: ")

print("\n--- Tarefa cadastrada ---")
print("ID:", id_tarefas)
print("Título:", titulo_tarefa)
print("Descrição:", descricao_tarefa)
print("Criação:", data_criacao)
print("Vencimento:", data_vencimento)
print("Prioridade:", prioridade)
print("Categoria:", categoria)
print("Usuário:", id_usuario)
print("Projeto:", id_projeto)
print("Cor:", cor_projeto)
print("Criado em:", criado_em)
