print("Cadastro de Comentário")

id_comentario = input("ID do comentário: ")
id_tarefa = input("ID da tarefa: ")
id_usuario = input("ID do usuário: ")
comentario = input("Comentário: ")
data_comentario = input("Data do comentário: ")
criado_em = input("Criado em: ")

print("\n--- Comentário cadastrado ---")
print("ID:", id_comentario)
print("Tarefa:", id_tarefa)
print("Usuário:", id_usuario)
print("Comentário:", comentario)
print("Data:", data_comentario)
print("Criado em:", criado_em)
