print("Cadastro de Métricas do Usuário")

id_metricas = input("ID da métrica: ")
id_usuario = input("ID do usuário: ")
data = input("Data: ")
tarefas_criadas = input("Tarefas criadas: ")
tarefas_concluidas = input("Tarefas concluídas: ")
dias_ativos = input("Dias ativos: ")
criado_em = input("Criado em: ")

print("\n--- Métrica cadastrada ---")
print("ID:", id_metricas)
print("Usuário:", id_usuario)
print("Data:", data)
print("Criadas:", tarefas_criadas)
print("Concluídas:", tarefas_concluidas)
print("Dias ativos:", dias_ativos)
print("Criado em:", criado_em)
