id_preferencia = input("Digite o ID da preferência: ")
id_usuario = input("Digite o ID do usuário: ")
tema = input("Digite o tema (claro/escuro): ")
notif_email = input("Receber notificações por email? (S/N): ")
notif_push = input("Receber notificações push? (S/N): ")
lembrete_padrao = input("Digite o lembrete padrão em minutos: ")

print("\n--- Preferências ---")
print("ID Preferência:", id_preferencia)
print("Usuário:", id_usuario)
print("Tema:", tema)
print("Notificação Email:", notif_email)
print("Notificação Push:", notif_push)
print("Lembrete Padrão:", lembrete_padrao, "min")
