id_tarefa = input("Digite o ID da tarefa: ")
data_inicio = input("Digite a data de início (AAAA-MM-DD): ")
data_fim = input("Digite a data de término (AAAA-MM-DD): ")
status = input("Digite o status (pendente/em andamento/concluída): ")
prioridade = input("Digite a prioridade (1 a 5): ")
id_usuario = input("Digite o ID do usuário: ")
id_projeto = input("Digite o ID do projeto: ")

print("\n--- Tarefa ---")
print("ID:", id_tarefa)
print("Data início:", data_inicio)
print("Data fim:", data_fim)
print("Status:", status)
print("Prioridade:", prioridade)
print("Usuário:", id_usuario)
print("Projeto:", id_projeto)
